### ISSUE TITLE
Cant access through webpage

### ISSUE THREAD

**Issue by AcidRain999** [chibicitiberiu/ytsm#36] opened 2018-11-06 13:32 UTC
i finally got the program to launch and it does say the server is running.

i try to browse to the address and it wont load. browser says there is nothing there
i am loading the program on debian and trying to access it from my laptop running windows

default user account hasnt been created yet since im stuck at the step in setup that says browse to server

**Comment by chibicitiberiu** [comment] 2018-11-07 10:51
How are you running? Are you using docker?

**Comment by chibicitiberiu** [comment] 2019-10-26 15:51
I'm closing this as I can't reproduce the issue, and I haven't gotten any answer.

**Closed by chibicitiberiu** 2019-10-26 15:51 UTC
Labels: bug, question
