### ISSUE TITLE
Dev branch does not refresh/sync/update

### ISSUE THREAD

**Issue by gerroon** [chibicitiberiu/ytsm#54] opened 2018-12-31 00:55 UTC
Hi

I am using the dev branch, and I see that none of my channels either updated or download all day at all. When I pres sync it says it schedules the sync, same with a custom download but no action is taken.

Does anyone else have this issue? 

This is the git head
commit 070755f119a225e5b802f6352b28e350e5fc46bc

**Comment by chibicitiberiu** [comment] 2018-12-31 10:43
I think I know what the problem is. After running the initial setup, the scheduler isn't started. Restarting the server should fix the issue. Can you test that after restarting the server it works?

**Comment by chibicitiberiu** [comment] 2018-12-31 11:55
Should be fixed in commit f879583.

**Comment by gerroon** [comment] 2018-12-31 16:53
You were right, I restarted it and it works now

**Closed** 2018-12-31 23:46 UTC
